---
title: "data wrangling"
author: "Iris Zhong"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load package}
library(here)
library(tidyverse)
library(dplyr)
```

```{r read data}
aqi19 <- read.csv(here("daily_aqi_by_county_2019.csv"))
aqi20 <- read.csv(here("daily_aqi_by_county_2020.csv"))
wind19 <- read.csv(here("daily_WIND_2019.csv"))
wind20 <- read.csv(here("daily_WIND_2020.csv"))
temp19 <- read.csv(here("daily_TEMP_2019.csv"))
temp20 <- read.csv(here("daily_TEMP_2020.csv"))
press19 <- read.csv(here("daily_press_2019.csv"))
press20 <- read.csv(here("daily_press_2020.csv"))
rhdp19 <- read.csv(here("daily_RH_DP_2019.csv"))
rhdp20 <- read.csv(here("daily_RH_DP_2020.csv"))
```

Data: 
2019: whole year
2020: weather measures - to 7/31
      aqi - to 8/31

```{r write weather function}
weather_clean_func <- function(data){
   name <- deparse(substitute(data))
   new_name <- paste(name,"cleaned",sep="_")
   data <- data %>%
    filter(State.Name == "Massachusetts",
           County.Name=="Suffolk") %>%
   mutate(date = as.Date(Date.Local)) %>%
   select(date, 
           site = Local.Site.Name, 
           mean = Arithmetic.Mean,
           unit = Units.of.Measure)
   assign(new_name, data, envir=.GlobalEnv)
}
```

```{r}
 wind19 %>%
    filter(State.Name == "Massachusetts",
           County.Name=="Suffolk")
```

**Note: wind is only measured in one site in both 2019 and 2020; It shows up twice because there are two units (knots vs. degrees compass).**
**wind 2020 no data from 7/14/2020**

```{r}
weather_clean_func(wind19)
weather_clean_func(wind20)
weather_clean_func(temp19)
weather_clean_func(temp20)
weather_clean_func(press19)
weather_clean_func(press20)
weather_clean_func(rhdp19)
weather_clean_func(rhdp20)
```

```{r write aqi function}
aqi_clean_func <- function(data){
   name <- deparse(substitute(data))
   new_name <- paste(name,"cleaned",sep="_")
   data <- data %>%
    filter(State.Name == "Massachusetts",
           county.Name=="Suffolk") %>%
    select(date = Date, 
           aqi = AQI)
   assign(new_name, data, envir=.GlobalEnv)
}
```


```{r}
aqi_clean_func(aqi19)
aqi_clean_func(aqi20)
```




